# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Clib' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clib

  pod 'RxSwift'
  pod 'RxCocoa'

  target 'ClibTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClibUITests' do
    # Pods for testing
  end

end
